name: Build Docker Image

on:
  push:
    branches:
      - main
      - master
      - develop
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest tests/unit

      - name: Run integration tests and generate HTML report
        run: |
          python -m pytest tests/integration --html=integration-report.html

      - name: Upload integration test report
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-report
          path: integration-report.html

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/devops_be-meshdefend-devops:latest
