name: Build Docker Image

on:
  push:
    paths:
      - 'DevOps_BE/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files for debugging
        run: |
          ls -l
          ls -l DevOps_BE

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t devops_be:latest ./DevOps_BE
